
default: &default
  adapter: postgresql
  encoding: unicode

development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

development:
   adapter: postgresql
   encoding: unicode
   database: yelp_development
   username: ""
   password: null

test:
   adapter: postgresql
   encoding: unicode
   database: yelp_test
   username: ""
   password: null

# production:
#    adapter: postgresql
#    encoding: unicode
#    database: yelp_production
#    username: rubyuser
#    password: <Password for rubyuser>
